Repository NCATSTranslator/ReasonerAPI, pull requests merged in 2020-10, with the labels that each got.

#153 Nest Message in Response
  TranslatorReasonerAPI.yaml
Labels: high severity

#151 Move edge relation from extended to core API
  TranslatorReasonerAPI.yaml
Labels: moderate severity

#163 realign with biolink model terms
  TranslatorReasonerAPI.yaml
Labels: enhancement

#164 Rename qnode.curie -> id
  TranslatorReasonerAPI.yaml
Labels: high severity
