Repository NCATSTranslator/ReasonerAPI, pull requests merged in 2020-08, with the labels that each got.

#128 Remove out-of-date files
  API/ReasonerStdAPI_0.8.0to0.9.0.pptx
  API/ReasonerStdAPI_0.8.0to0.9.1.pptx
  API/TranslatorReasonersAPI_swagger2.0.yaml
Labels: low severity

#129 Update policies: experimental -> extended
  Policies.md
Labels: low severity

#139 Add alternative bypass_cache
  API/TranslatorReasonersAPI.yaml
Labels: moderate severity

#140 Add explicit HTTP status codes
  API/TranslatorReasonersAPI.yaml
Labels: moderate severity

#136 Use CURIEs as types
  API/TranslatorReasonersAPI.yaml
Labels: high severity

#141 Edit the top-level README with current information
  README.md
Labels: low severity

#131 A first step toward updating the documentation
  API/README.md
Labels: low severity
