Repository NCATSTranslator/ReasonerAPI, pull requests merged in 2020-07, with the labels that each got.

#113 Enforce styling
  .yamllint.yml
  API/TranslatorReasonersAPI.yaml
  tox.ini
Labels: low severity

#109 use 'node_attributes' in place of additionalProperties
  API/TranslatorReasonersAPI.yaml
Labels: high severity

#112 Add EdgeAttribute only
  API/TranslatorReasonersAPI.yaml
Labels: high severity

#118 add a mechanism to provide logging information
  API/TranslatorReasonersAPI.yaml
Labels: moderate severity

#122 Bump version of experimental to 0.9.3-dev
  API/TranslatorReasonersAPI.yaml
Labels: experimental

#121 Bump the version to 0.9.3-dev as per new docs
  API/TranslatorReasonersAPI.yaml
Labels: low severity

#114 Added "translator" and "reasoner" tags
  API/TranslatorReasonersAPI.yaml
Labels: low severity
